config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # resources :restaurants
  # resources :reviews, only: [:new, :create]
  # Defines the root path route ("/")
  # root "articles#index"
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new"
  post "restaurants", to: "restaurants#create"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  get "restaurants/:restaurant_id/reviews/new", to: "reviews#new", as: :restaurant_new_review
  post "restaurants/:restaurant_id/reviews", to: "reviews#create", as: :restaurant_reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  CATEGORY = %w[ chinese italian japanese french belgian ]
  validates :category, presence: true, inclusion: { in: CATEGORY}

  has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { within: 0..5 }
  validates :rating, numericality: { only_integer: true }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    @restaurant.save
    redirect_to @restaurant, notice: "Restaurant was successfully created."

  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save!
    redirect_to restaurant_path(@restaurant)
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>
  <%= f.label :address %>
  <%= f.text_field :address %> <br>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %> <br>
  <%= f.label :category, collection: Restaurant::CATEGORY  %>
  <%= f.text_field :category, collection: Restaurant::CATEGORY %><br>
  <%= f.submit "Add new restaurant", class: "btn-btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">
<h1>Restaurants</h1>

<% @restaurants.each do |restau| %>
<ul>
  <li><%= link_to restau.name, restaurant_path(restau) %></li>
  <li><%= restau.address %></li>
  <li><%= restau.phone_number %></li>
  <li><%= restau.category %></li>
</ul>
  <% end %>

<p><%= link_to "Add a new restaurant", restaurants_new_path  %></p>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
  <p>
    <strong><%= @restaurant.name %></strong>

  </p>

  <p>Address:
    <%= @restaurant.address %>
  </p>

  <p>Phone number:
    <%= @restaurant.phone_number %>
  </p>

  <p>Category:
    <%= @restaurant.category %>
  </p>

  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
      <%= review.content %>
      <%= review.rating %></li>
    <% end %>
  </ul>
<br>


</div>

<p><%= link_to "Back to all restaurants", restaurants_path  %></p>
<%= link_to "Write a new review", restaurant_new_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>